### PR TITLE
Marking connection as not released

### PR DESCRIPTION
**Pull request by maxmzkr**
https://github.com/cloudera/ibis/issues/871

When a connection is removed from the connection pool, mark released as False as it is no longer released.

### CODE REVIEW

**Comment by maxmzkr** [comment]
Is there instructions on how to run tests locally?

**Comment by cpcloud** [comment]
`py.test` from your ibis clone should do the trick.

**Comment by wesm** [comment]
You need to run `py.test ibis --impala`; it will require setting some environment variables to connect to your test cluster properly. We hope to have a fully-functional Dockerfile to use for running the test suite.

What is the status of this patch? Something I can look at next week?

**Comment by maxmzkr** [comment]
I've been distracted by other things at work. I'm working on getting my
environment setup so I can make sure the tests pass.

**Comment by wesm** [comment]
I can also verify the patch if need be as I have a working test environment, but I'm sure it'd be useful for you to have an env set up. If we can get a ready-to-go docker image pushed to dockerhub that would be ideal.

**Comment by maxmzkr** [comment]
I'm fine with that

**Comment by wesm** [comment]
Any way to write a test case for this?

**Comment by maxmzkr** [comment]
Yup.

**Comment by maxmzkr** [comment]
This should be all set to go!

**Comment by wesm** [comment]
I had to make a minor tweak to get the test suite passing but this is good now. Thank you!

**Pull request closed without merging**
