### PR TITLE
TST: Jenkins script must pass prospector (flake8) or fail

### LINKED ISSUE #616: Add prospector run to jenkins job
flake8/pylint violations will fail the jenkins build.

### PR DESCRIPTION
**Pull request by laserson**
Fixes #616.

### CODE REVIEW

**Comment by laserson** [comment]
Let me run this through the sandbox job.  Note that after merging this, any prospector/flake8 violations will fail the Jenkins build.

**Comment by laserson** [comment]
Python 3 errors:

```
ibis/wire.py
  Line: 32
    pyflakes: F821 / undefined name 'basestring' (col 28)

scripts/airline.py
  Line: 13
    pyflakes: F999 / invalid syntax (col 29)

scripts/test_data_admin.py
  Line: 232
    pyflakes: F821 / undefined name 'xrange' (col 54)
  Line: 238
    pyflakes: F821 / undefined name 'xrange' (col 14)
```

**Comment by laserson** [comment]
Is `ibis/wire.py` codegen?

**Comment by wesm** [comment]
no, you can exclude it from the run, also anything under scripts/

**Comment by laserson** [comment]
@wesm note this is merged now

**Pull request merged**
