### PR TITLE
WIP/BUG: Fix sqla filter bug

### PR DESCRIPTION
**Pull request by cpcloud**
Only a failing test ATM

### CODE REVIEW

**Comment by wesm** [comment]
Started looking at this finally. The fix is surprisingly not obvious; the compiled SELECT query is not quite right and it only happens to produce the right query in the Impala compiler by accident.

**Comment by cpcloud** [comment]
There was a commit that introduced a rewrite of projections from `t[column]` to `t[[column]]`. I don't remember exactly where, but hopefully that helps narrow it down.

**Comment by wesm** [comment]
Yeah, I think I found the problem, I need to do some other cleaning to fix it, will see what I can do in the next hour or so

**Comment by wesm** [comment]
Compilers are hard. This took me a while to figure out but should be good now

**Pull request closed without merging**
