### PR TITLE
ENH: Add conda recipes for Ibis and deps

### PR DESCRIPTION
**Pull request by koverholt**
Addresses #382. Tested on linux-64 and osx-64 arches. Conda packages are available at https://anaconda.org/koverholt for testing using:

```
conda install -c koverholt ibis-framework
```

### CODE REVIEW

**Comment by wesm** [comment]
Awesome! if you or someone can follow up with me regarding a CLA, that would be great: http://docs.ibis-project.org/developer.html#contributor-license-agreements

**Comment by koverholt** [comment]
Great, thanks! We'll be in touch soon regarding the CLA.

**Comment by wesm** [comment]
thanks, we're all set. I'll review and merge this later today

**Comment by wesm** [comment]
Seems there are a lot of packages here that aren't used in the library, can you remove them? I also removed snakebite from the requirements.txt (I never ended up using it). thanks!

**Comment by koverholt** [comment]
I updated the hdfs version and removed the recipes for snakebite and its dependencies (tox and pluggy).

Using only hdfs (with no extras), the following base conda packages required for Ibis:
* avro
* hdfs
* ibis-framework
* impyla
* thrift

Adding hdfs[kerberos] per the requirements.txt adds the following package dependencies:
* fastavro
* kerberos
* requests-kerberos

Usually, we create a `conda.recipe` folder for the primary package and a `conda-recipes` folder for the dependencies. This way you can manage all of the recipes from your repo. Let me know if you want me to organize the recipes this way.

I uploaded the new packages to my channel on [Anaconda.org] (https://www.anaconda.org/koverholt), so you can test with:

```
conda install -c koverholt ibis-framework
```

**Comment by wesm** [comment]
We removed `hdfs[kerberos]` from the requirements (which is hard to install on Windows, anyway), and so there are no avro or kerberos dependencies anymore. It might have changed only recently in mtth/hdfs, though https://github.com/mtth/hdfs/blob/master/setup.py

**Comment by koverholt** [comment]
Thanks, I missed the commit where you removed `hdfs[kerberos]`. If I remove the `hdfs[kerberos]` requirement and remove the following avro entrypoint/test from the hdfs recipe (I assume you don't need this functionality?):

```
build:
  entry_points:
    - hdfs-avro = hdfs.ext.avro:main

test:
  commands:
    - hdfs-avro --help
```

then the resulting dependencies/recipes for Ibis are:
* hdfs
* ibis-framework
* impyla
* thrift

My most recent commit does this and all of the Ibis tests are passing on osx-64 and linux-64 using these four packages/recipes.

**Comment by wesm** [comment]
awesome, thank you!

**Pull request closed without merging**
