### PR TITLE
Update conda recipes for Ibis 0.6.0

### PR DESCRIPTION
**Pull request by koverholt**
Built and tested with Python 2.7 and Python 3.4 on osx-64, linux-64, and win-64.

Conda packages for Ibis 0.6.0 can be installed using:

```
conda install ibis-framework -c koverholt
```

### CODE REVIEW

**Comment by koverholt** [comment]
The first commit contains recipes for Ibis 0.6.0 from PyPI, and the second commit restores the edits from #712 to pull from trunk (apologies, I initially didn't see those edits).

Either way, the conda packages for Ibis 0.6.0 are available at the above conda channel.

**Comment by mariusvniekerk** [comment]
These changes also allow py34 / 35? builds

**Comment by koverholt** [comment]
I only tested with and built py27 and py34 packages at the moment.

**Comment by wesm** [comment]
Sorry I've been slow on this. Will merge, but are some Python 3.x issues with the library stack (API changes in thriftpy as far as I can tell), but we can address those after I get everything working

**Comment by wesm** [comment]
@mariusvniekerk I've moved to 3.5 for my primary development environment finally, so should have better ongoing support for 3.x. Lot of Hadoop users are still stuck on 2.x though.

**Comment by mariusvniekerk** [comment]
Yeah 3.5 is much nicer. I'm still stuck on 2.7 myself. (Thrift dependencies
using protocols not in thriftpy yet). I'll update the recipes to make
Thrift a 2.x only requirement.

**Pull request closed without merging**
