### PR TITLE
Add chmod and chown to HDFS clients

### LINKED ISSUE #446: Enable chmod and chown operations through HDFS interface

### PR DESCRIPTION
**Pull request by ihodes**
I'm not able to run tests right now (working on setting up a personal cluster to amend this), so this is a WIP until I can run tests.

fixes #446

### CODE REVIEW

**Comment by wesm** [comment]
I just tried running the tests -- using `set_ownership` requires a secure connection. @laserson what do you think is the easiest way to effect this in the unit tests (perhaps avoiding kerberos if we can)?

**Comment by ihodes** [comment]
I spent a little time with this today; not sure what the best way to do this is. The real issue is actually below (the previous error being displayed was a result of a typo; that is now fixed). I'm traveling for a bit, so will be pretty slow in working on this. 

```
{"RemoteException":{"message":"Non-super user cannot change owner","exception":"AccessControlException","javaClassName":"org.apache.hadoop.security.AccessControlException"}}
```

**Comment by wesm** [comment]
I'm superuser in my dev environment, let me have a look.

**Comment by wesm** [comment]
Opening and merging a new PR

**Comment by ihodes** [comment]
Awesome, thank you!

**Pull request closed without merging**
