### PR TITLE
Add dockerized impala instance to CI

### LINKED ISSUE #935: VarArgs has no attribute types
Exposed by running impala tests

### PR DESCRIPTION
**Pull request by cpcloud**
its-over-its-q96aop

Closes #935

### CODE REVIEW

**Comment by mjacobs** [comment]
@wesm sorry I wasn't following along - what were the major pain points here?

**Comment by wesm** [comment]
I'll let @cpcloud comment in more detail since he did the work -- but among other things I think he had to build his own docker image. It would be great to collaborate with the Impala team to maintain an official Dockerfile (if one does not already exist) to enable 3rd-party applications to develop against Impala releases and Impala trunk more easily. In this patch there are a number of other details that had to be sorted out to make the Docker image we built work reliably in a CI setting

**Comment by cpcloud** [comment]
@mjacobs @wesm It's been a while since I tried to use the impala docker image, but I ultimately went with the one we're using because it doesn't require me to build impala from scratch. Building impala from scratch takes way too long to iterate on for the purpose of just send queries to impala.

We don't need bleeding edge builds for ibis, just nothing extremely old.

For better or worse the docker image I made is pulling `http://archive.cloudera.com/cdh5/one-click-install/trusty/amd64/cdh5-repository_1.0_all.deb` and installing packages from that.

This nearly worked out of the box. The rest of the time was spent understand docker and how to use it in the circle-ci context and how to get ibis to talk to the impala server (what environment variables I needed to use mostly). CircleCI doesn't have docker exec, so that was fun.

I also did this work in bursts, so it took a long time because I worked on it sporadically.

Here's the docker image I'm using: https://hub.docker.com/r/cpcloud86/impala

**Comment by mariusvniekerk** [comment]
Amazing

**Pull request closed without merging**
